# -*- coding: utf-8 -*-
"""Copy of HW 1.1 Основи статистики.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VUeoXPZb-oSfvTmYbpL8hBCW26mwYEm

В цьому домашньому завданні відпрацюємо з вами знання, отримані в модулі зі статистики.

**Завдання 1.** Ми обговорили з Вами на лекції, що велика літера Сігма грецького алфавіту позначає в математиці суму. Знайдіть з використанням Python $\Sigma x$, $\Sigma x^2$, та $\Sigma (x-1)^2$ для наступного набору даних:
`1 3 4`
Виведіть результат кожного обчислення на екран.
"""

# Σ𝑥
x=[1,2,3]
sum_x = sum(x)
print("Σ𝑥:",sum_x)
# Σ𝑥2
sum_x_square_list = [n**2 for n in x]
sum_x_square = sum(sum_x_square_list)
print("Σ𝑥2:", sum_x_square)
# Σ(𝑥−1)2
sum_x1_list = [(n-1)**2 for n in x]
sum_x1 = sum(sum_x1_list)
print("Σ(𝑥−1)2:",sum_x1)

"""**Завдання 2.** Ми зібрали дані про суму покупок в гривнях 20ма випадково обраними клієнтами в нашому магазині (всього клієнтів у нас більше) за минулий місяць. Вони представлені в змінній `sum_purchases`. Знайдіть **вибіркове середнє** для цих даних кожним з зазначених методів:   

  2.1. без використання жодних бібліотек, користуючись тільки Python.  
  2.2. використовуючи відповідний метод бібліотеки `numpy`.

  Виведіть результат обчислень в кожному з випадків на екран та порівняйте результати. Вони співпадають?
"""

sum_purchases= [ 316,  493,  367,  153,  224,  121,  322,  450,  196,  397,  281,
  239,  484,  124,  223,  448,  432,  255, 4310, 3524]

# 2.2. Bикористовуючи відповідний метод бібліотеки numpy.
import numpy as np
print ("Bибіркове середнє:",np.mean(sum_purchases))

# 2.1. без використання жодних бібліотек, користуючись тільки Python.
n_sum_purchases = len(sum_purchases)
sum_p = sum(sum_purchases)
mean_sum_purchases = sum_p/n_sum_purchases
print("Bибіркове середнє:",mean_sum_purchases)

"""**Завдання 3.** Для того ж набору даних в змінній `sum_purchases` обчисліть **медіану** кожним з зазначених методів:  

  3.1. без використання жодних бібліотек, користуючись тільки Python.  
  3.2. використовуючи відповідний метод бібліотеки numpy.  

Виведіть результат обчислень в кожному з випадків на екран. Порівняйте результати зі значенням вибіркового середнього. Напишіть коментар, для яких задач ви б використовували вибіркове середнє, а для яких - медіану?
"""

# 3.2. Використовуючи відповідний метод бібліотеки numpy.
print("Mediana:",np.median(sum_purchases))

# 3.1. Без використання жодних бібліотек, користуючись тільки Python.

sorted_list = sorted(sum_purchases)
display(len(sorted_list))
print(len(sorted_list)//2-1,len(sorted_list)//2)
print("Median:",(sorted_list[len(sorted_list)//2-1]+sorted_list[len(sorted_list)//2])/2)

"""**Завдання 4**. Обчислість стандартне відхилення наведеної вибірки в змінній `sum_purchases` кожним з зазначених методів:  

  4.1. без використання жодних бібліотек, користуючись тільки Python.  
  4.2. використовуючи відповідний метод бібліотеки numpy.  

Виведіть результат обчислень в кожному з випадків на екран.
"""

# 4.2. використовуючи відповідний метод бібліотеки numpy.
print("Cтандартне відхилення:",np.std(sum_purchases,ddof=1))

# 4.1. без використання жодних бібліотек, користуючись тільки Python.
x_minus_mean_list = [(n-mean_sum_purchases)**2 for n in sum_purchases]
sum_x_minus_mean = sum(x_minus_mean_list)
var = sum_x_minus_mean/(len(sum_purchases)-1)
std_purchases = var**0.5
print("Cтандартне відхилення:",std_purchases)

"""**Завдання 5**. Ми провели дослідження віку студентів-першокурсників. Виявилось, що
- 10 студентів мають вік 16 років
- 25 студентів - 17 років
- 20 студентів - 18 років
- 2 студенти - 20 років

Обчислість середнє значення для цієї вибірки будь-яким способом - на чистому Python або з numpy - та виведіть результат на екран.
"""

x = ([16]*10+[17]*25+[18]*20+[20]*2)
print ("Mean:",np.mean(x))

"""**Завдання 6**. Крім даних про суму покупок, ми зібрали ще дані про кількість відвідувань кожного з кожного покупця, які знаходяться в змінній `visits`. Обчисліть коефіцієнт кореляції Пірсона для суми покупок і кількості відвідувань кожним з зазначених методів:  

  6.1. без використання жодних бібліотек, користуючись тільки Python.  
  6.2. використовуючи відповідний метод бібліотеки numpy.  
  
Виведіть результат на екран. Проаналізуйте результат.

Виведіть додатково графік розсіювання викликавши код нижче і зробіть заключення, чи варто щось змінити при підрахунку кореляції, аби коефіцієнт Пірсона показував коректну оцінку лінійної залежності?
"""

visits = [ 6,  2, 10,  3,  9,  9,  2,  3,  6,  6, 10,  2,  5, 10,  3,  5,  4,
        7,  4,  2]

# Обчисліть коефіцієнт кореляції Пірсона для суми покупок і кількості відвідувань
# без використання жодних бібліотек, користуючись тільки Python.

mean_visits = sum(visits)/len(visits)
visits_minus_mean = [(i-mean_visits)**2 for i in visits]
sum_visits_minus_mean = sum(visits_minus_mean)
std_visits = (sum_visits_minus_mean/(len(visits)-1))**0.5
print("STD_visits_py:",std_visits)
purchases_visits_multiply = [(sum_purchases[i]-mean_sum_purchases)*(visits[i]-mean_visits) for i in range (len(sum_purchases))]
cov = sum(purchases_visits_multiply)/(len(sum_purchases)-1)
print("Коваріація:",cov)
corr_visits_purchases =cov/(std_visits*std_purchases)
print("Кореляція:",corr_visits_purchases)

# Обчисліть коефіцієнт кореляції Пірсона для суми покупок і кількості відвідувань
# використовуючи відповідний метод бібліотеки numpy.

print("STD_visits_np:",np.std(visits))
print ("Коваріація:",np.cov(sum_purchases,visits))
np.corrcoef(sum_purchases,visits)
print("Кореляція:",np.corrcoef(sum_purchases,visits))

import matplotlib.pyplot as plt

plt.scatter(sum_purchases, visits)
plt.title('Scatter Plot of Purchases vs. Visits')
plt.xlabel('Sum of Purchases')
plt.ylabel('Number of Visits');

# There is weak positive correlation btw sum of purchses and number of visits which means that sum of purchases slightly raises in case of more frequent store visits.
# To improve the results, we might try to remove extreme values from our sample and attempt to adjust the distribution to match one of the known types. This would allow us to use appropriate statistical methods for further investigation.
# Also we might try to extend our sample and analyse bigger scale.

"""**Завдання 7**. В попередньому завданні ми помітили, що викиди нам заважають отримати "правдиве" значення кореляції. Давайте вилучимо записи, які відповідають значенням з викидами в сумі покупок і обчисліть коеф. кореляції. Для цього поставте `threshold`, який дорінює середньому значенню + 2 стандартних вдіхилля суми покупок і всі значення, які більше за нього, будемо вважати викидами (є і інші правила для визначення викидів - з ним и познайомимось пізніше).

Вилучіть значення з обох масивів і обчисліть коеф. кореляції Пірсона з допомогою `numpy` для кількості візитів і суми покупок без записів-викидів. Виведіть результат на екран, побудуйте діаграму розсіювання і проаналізуйте результат: що можемо сказати про залежність в даних?
"""

threshold = mean_sum_purchases+2*std_purchases
filtered = list(filter(lambda pair: pair[0] <= threshold, zip(sum_purchases, visits)))
filtered_purchases = [x for x, y in filtered]
filtered_visits = [y for x, y in filtered]
print("Kоеф. кореляції Пірсона:", np.corrcoef(filtered_visits,filtered_purchases))

plt.scatter(filtered_purchases, filtered_visits)
plt.title('Scatter Plot of Purchases vs. Visits')
plt.xlabel('Sum of Purchases')
plt.ylabel('Number of Visits');

# Removing extreme numbers slightly helped to improve correlation result. However, sample correlation is still weak, less than 0.5.Correlation of 0.3 indicates a weak relationship, which does not allow for confident predictions: an increase in the sum of purchases is not always accompanied by an increase in the number of visits, and vice versa.